// High-detail battle sprites for the Phantom Legion.
// Every adversary's design tells you what identity attack it is.
import { compile, glitchify, scale2x, shade } from './palette.js';

// Pixel-art finishing pipeline: double resolution with rounded contours,
// then bake in top-lit volumetric shading. GBA polish for hand-set pixels.
const polish = (cv) => shade(scale2x(cv));

// PHISH KOI 38x24 — fat koi, white belly, orange patches, a hook in its lip
// trailing line, blowing a bubble. The entry-level lure.
const PHISHKOI = [
  '............y.........................',
  '............y.............kk..........',
  '............y............kzzk.........',
  '............y.............kk..........',
  '.............kkkkkkkkkk...............',
  '..........kkkooooooooookk.............',
  '........kkoooowwooooooooOkk....kkk....',
  '.......koooooowwkoooooooOOOk..kooOk...',
  '......koowoooooooooOOoooooOOkkoooOk...',
  '.....koowwoooooooooOOooooooookooOOk...',
  '....kowwooookwkoooooooOOoooookoOOk....',
  '....kowoooookkooooooooOOooooookOOk....',
  '...kwwooooooooooooooooooooooookOOk....',
  '...kwykwwwwwwwwwooooOOooooookooOk.....',
  '...kyykwwwwwwwwwwoooooooooookoOOk.....',
  '....ky.kwwwwwwwwwwooooooookkooOk......',
  '....k...kkwwwwwwwwwwoookkkoooOk.......',
  '..........kkkwwwwwkkkk..koooOk........',
  '.....kOok....kkkkk........koOk........',
  '....koooOk.................kk.........',
  '.....kOOk.............................',
  '......kk..............................',
];
// SPEAR-PHISH 42x18 — barracuda with a steel spear snout: dorsal fin rays,
// gill slit, lateral scale specks, pale belly, glinting eye.
const SPEARPHISH = [
  '.....................kkkkkk............',
  '....................kbBkbBkk...........',
  '..................kkbbbbbbbbkk.........',
  '..............kkkkbbbbbbbbbbbbk..kkk...',
  '...........kkbbbbbbbbbbbbbbbbbbkkbbBk..',
  '..........kbbbbwkkbbbbbbBbbbbbbkbbbBk..',
  '...........kkbbwkwbbbbbbbbBbbbbbkbbbk..',
  'kkkkkkkkkkkmkbbbbbbbkbbbbbbbbbbkbbbBk..',
  'cmmmmmmmmmmcmkbbbbbbkbbbBbbBbbbkkbbbk..',
  'kkkkkkkkkkkmkwwbbbbbkbbbbbbbbbkbkbBk...',
  '..........kwwwwwwbbbbbbbBbbbbbkbbbk....',
  '...........kkwwwwwwbbbbbbbbbkkkbBk.....',
  '..............kkwwwwbbbbbbbbk..kk......',
  '..................kkkkbBkbBkk..........',
  '......................kkkkkk...........',
  '..w..w..................................',
  'ww..ww..................................',
];
// LURE ANGLER 38x28 — deep-sea horror dangling a glowing FAKE LOGIN WINDOW.
const ANGLER = [
  '....................kk................',
  '...................kqk.................',
  '..................kqk..................',
  '.................kqk...................',
  '......kkkkkkk....kqk...................',
  '.....kIIIIIIIk..kqk....................',
  '.....kIwwwwwIk..kqk....................',
  '.....kIwttwwIkkkqk.....................',
  '.....kIwwwwwIk.........................',
  '.....kIIyyIIIk.........................',
  '......kkkkkkk..kkkkkk..................',
  '.............kkqqqqqqkkk...............',
  '..........kkqqqqqqqqqqqqkk......kkk....',
  '........kqqqqwwkqqqqqqqqqqk....kqqdk...',
  '.......kqqqqqwwkqqqqdqqqqqqk..kqqdk....',
  '......kqwkwkwkqqqqqqqqdqqqqkkqqqdk.....',
  '......kqkwkwkwkqqqqqqqqqqqqkqqqdk......',
  '......kqwkwkwkqqqqdqqqqqqqkqqqqdk......',
  '.......kqqqqqqqqqqqqdqqqqqkkqqdk.......',
  '........kqqqqqqqqqqqqqqqkk..kqdk.......',
  '..........kkqqqqqqqqqkkk.....kk........',
  '.............kkkkkkkk..................',
];
// LAZARUS MASK 28x30 — too-perfect candidate: suit, cracked theater mask,
// briefcase stuffed with identical resumes.
const LAZARUS = [
  '.........kkkkkkkk...........',
  '........kkkkkkkkkk..........',
  '........kwwwwwwwwk..........',
  '........kwwkwwkwwk..........',
  '........kwwwwwwwwk.........',
  '........kwwwkkwwwk..........',
  '........kwwwwwwkwk..........',
  '.........kwwwwkwk...........',
  '..........kkkkkk............',
  '........kjjjjjjjjk..........',
  '......kjjjwwwwwwjjjk........',
  '.....kjjjjwwrrwwjjjjk.......',
  '.....kjJjjwwwwwwjjJjk.......',
  '.....ksjjjjjjjjjjjjsk.......',
  '.....ksjjjjjjjjjjjjsk.......',
  '......kjjjjjjjjjjjjk........',
  '......kjjjjjjjjjjjk.........',
  '......kjjjkkkkjjjjk..kkkkk..',
  '......kjjjjjjjjjjjk.kYwwwYk.',
  '......kjjjj..jjjjk..kYwwwYk.',
  '......kjjjk..kjjjk..kYYYYYk.',
  '......kkkk....kkkk..kkkkkkk.',
];
// VISHING IMP 32x26 — grinning imp tangled in its own phone cord,
// old handset pressed to its ear.
const VISHIMP = [
  '....kk............kk............',
  '...krrk..........krrk...........',
  '...krrrk........krrrk...........',
  '....krrrkkkkkkkkrrrk............',
  '....krrrrrrrrrrrrrk.............',
  '...krrrwwkrrrrwwkrrk....kkkk....',
  '...krrrwkkrrrrwkkrrk...kmmcmk...',
  '...krrrrrrrrrrrrrrrk...kmcmk....',
  '...krrkwwwwwwwwkrrrkkkkmmck.....',
  '....krrrwkkkkwrrrrk..NNkmk......',
  '.....krrrrrrrrrrrk..N..kk.......',
  '....krrrrrrrrrrrrk..N...........',
  '...krrrrkrrrrkrrrrk.N...........',
  '...ksrrrkrrrrkrrsk..N...........',
  '....kkrrrrrrrrrkk..N............',
  '.....krrrrrrrrrk..N.............',
  '.....krrkrrrkrrkNN..............',
  '....krrk.krrk.krrk..............',
  '....krk...krk..krk..............',
  '....kk....kk....kk..............',
];
// PUSH BOMBER 32x26 — imp juggling notification bombs, each one a red
// badge with a white exclamation. TAP TAP TAP.
const PUSHBOMBER = [
  '..kkk..........kkk......kkk.....',
  '.krrrk........krrrk....krrrk....',
  '.krwrk........krwrk....krwrk....',
  '.krrrk........krrrk....krrrk....',
  '..kkk..........kkk......kkk.....',
  '......kkkkkkkkkk................',
  '.....kvvvvvvvvvvk...............',
  '....kvvwwkvvwwkvvk..............',
  '....kvvwkkvvwkkvvk..............',
  '....kvvvvvvvvvvvvk..............',
  '....kvkwwwwwwkvvvk..............',
  '.....kvvkkkkvvvvk...............',
  '....kvvvvvvvvvvvvk..............',
  '...kvvvvkvvvvkvvvvk.............',
  '...ksvvvkvvvvkvvsk..............',
  '....kkvvvvvvvvvkk...............',
  '.....kvvvvvvvvvk................',
  '.....kvvkvvvkvvk................',
  '....kvvk.kvvk.kvvk..............',
  '....kvk...kvk..kvk..............',
  '....kk....kk....kk..............',
];
// KEYLOGGER SPIDER 36x26 — spider whose abdomen is a keyboard keycap,
// legs poised over a row of keys.
const KEYLOGGER = [
  '...k.....k........k.....k...........',
  '....k...kqk......kqk...k............',
  '.....k.kqqqk....kqqqk.k.............',
  '......kqqqqqkkkkqqqqqk..............',
  '.....kqqqqqqqqqqqqqqqk..............',
  '....kqqrrkqqqqqqkrrqqqk.............',
  '....kqqrkkqqqqqqkkrqqqk.............',
  '....kqqqqqqkkkkqqqqqqqk.............',
  '.....kqqqqkwwwwkqqqqqk..............',
  '...kkkqqqqqkkkkqqqqqkkk.............',
  '..k...kkkkkkkkkkkkkk...k............',
  '.k...kmcccccccccccccmk..k...........',
  '.....kmcwkkkkkkkkwccmk..............',
  '.....kmcwk.K.K.kkwccmk..............',
  '.....kmcwkkkkkkkkwccmk..............',
  '.....kmcccccccccccccmk..............',
  '.....kmmmmmmmmmmmmmmmk..............',
  '..kkkkkkkkkkkkkkkkkkkkkkk...........',
  '..kcckkcckkcckkcckkcckkck...........',
  '..kkkkkkkkkkkkkkkkkkkkkkk...........',
];
// TOKEN THIEF 30x30 — hooded snatcher holding a stolen, still-glowing
// session token, loot bag over the shoulder.
const TOKENTHIEF = [
  '.........kkkkkkkk.............',
  '........kqqqqqqqqk............',
  '.......kqqqqqqqqqqk...........',
  '......kqqqqqqqqqqqqk..........',
  '......kqqekkkkkkeqqk..........',
  '......kqekwk..kwkeqk..........',
  '......kqeeeeeeeeeeqk..........',
  '......kqqeeekkeeeqqk..........',
  '.......kqqqeeeeqqqk...........',
  '......kqqqqqqqqqqqqk....kkk...',
  '.....kqqqqqqqqqqqqqqk..kyzyk..',
  '....kqqqqqqqqqqqqqqsk.kyzzzyk.',
  '...kqqqkqqqqqqqkqqssk.kyzzzyk.',
  '...kqqk.kqqqqqk.kqsk...kyzyk..',
  '...kqk..kqqqqqk..ss.....kkk...',
  '...kNNkkqqqqqqqk..............',
  '..kNNNNkqqqqqqqk..............',
  '..kNNNNkqqqqqqqk..............',
  '...kNNk.kqqqqqk...............',
  '....kk..kqqkqqk...............',
  '........kqk.kqk...............',
  '........kk...kk...............',
];
// SIM SHIFTER 34x24 — gooey shapeshifter mid-morph, two half-faces,
// triumphantly holding up a stolen SIM.
const SIMSHIFT = [
  '..........kkkkkkkk..............',
  '.......kkkffffffffkk............',
  '.....kkfffffffffffffkk..........',
  '....kfffffffffkffffffk....kkk...',
  '...kffwwkfffffkffwkffk...kyygk..',
  '...kffwkkfffffkfwkkffk...kygyk..',
  '...kffffffffffkffffffk...kyyyk..',
  '...kfffkkkffffkfkkfffk...kkkk...',
  '....kffffffffffffffffkkkkfk.....',
  '...kffffkkkkkffffffffffffk......',
  '..kfffffffffffkffffffffk........',
  '..kffffffffffffkffffffk.........',
  '..kffkfffffkffffffkfffk.........',
  '.kfff.kffffk.kffffk.fffk........',
  '.kff...kfffk..kffk...ffk........',
  '..kf....kfk....kk.....fk........',
  '...k.....k.............k........',
];
// CRED STUFFER ZOMBIE 30x30 — shambling reuse incarnate: huge keyring,
// keys dropping, tattered lanyard badge.
const STUFFERZOMBIE = [
  '.....gggggg...................',
  '....gggggggg..................',
  '...gggssssgg..................',
  '...sgsssssssg.................',
  '...sskksskkss.................',
  '...ssskssksss.................',
  '....ssssssss..................',
  '....sskkkkss..................',
  '...ccccccccc..................',
  '..ccccccccccc.....kk..........',
  '.scccwwcccccss...kyyk.........',
  '.sccwwwwccccss..kyykyk........',
  '..ccwrwwccccc...kyk.kyk.......',
  '..ccwwwwccccc..kyyk..k........',
  '..cccccccccccykyk.............',
  '..ccccccccccyyky..y...........',
  '...ccccccccc..ky..y...........',
  '...NNNNNNNNN...k..............',
  '...NNNkkNNNN..................',
  '...NNN..NNNN..................',
  '...sss...sss..................',
  '...kkk...kkk..................',
  '..kkkk...kkkk.................',
];
// ROGUE AGENT 32x26 — unsanctioned drone: single great eye, claw
// manipulators, a torn policy seal on its hull.
const ROGUEAGENT = [
  '...........kkkkkk...............',
  '.........kkmmmmmmkk.............',
  '........kmmmmmmmmmmk............',
  '.......kmmmkkkkkkmmmk...........',
  '.......kmmkzzzzzzkmmk...........',
  '.......kmmkzkkzzzkmmk...........',
  '.......kmmkzzzzzzkmmk...........',
  '.......kmmmkkkkkkmmmk...........',
  '......kmmmmmmmmmmmmmmk..........',
  '......kmMrkkmmmmmmMmmk..........',
  '......kmMkrkmmmmmmMmmk..........',
  '.......kmmmmkkkkmmmmk...........',
  '....kk.kmmmmmmmmmmmk.kk.........',
  '...kzzkkmmkmmmmkmmkkzzk.........',
  '....kk.kmk.kmmk.kmk.kk..........',
  '.......kk..kmmk..kk.............',
  '......kmk...kk...kmk............',
  '.....kmclk......klcmk...........',
  '.....kkkk........kkkk...........',
];
// ------------------------------------------------------------ BOSSES
// THE PHISHER KING 52x30 — crowned monarch of lures: golden crown,
// royal cape-fin, jagged teeth, scepter dangling a fake login window.
const PHISHERKING = [
  '...............y..y..y......................',
  '...............kyykyyk......................',
  '...............kyyyyyk......................',
  '............kkkqqqqqqkkk....................',
  '..........kkqqqqqqqqqqqqkk..................',
  '........kkqqqqqqqqqqqqqqqqkk......kkk.......',
  '.......kqqqqwwkqqqqqqqdqqqqqk....kqqdk......',
  '......kqqqqqwwkqqqqqqqqqdqqqqk..kqqddk......',
  '.....kqqqqqqqqqqqdqqqqqqqqqqqkkqqqddk.......',
  '....kqdqqqqqqqqqqqqqdqqqqqqqqkqqqddk........',
  '....kqwkwkwkwkqqqqqqqqqdqqqqqkqqqdk.........',
  '....kqkwkwkwkwkqqqqqqqqqqqqqqkqqqdk.........',
  '....kqwkwkwkwkqqqqdqqqqqqqqqkqqqddk.........',
  '.....kqqqqqqqqqqqqqqqdqqqqqqkkqqddk.........',
  '......kqqqqqqqqqqqqqqqqqqqkk..kqdk..........',
  '.......kkqqqqqqqqdqqqqqkkk.....kk...........',
  '.........kkkqqqqqqqkkkk.....................',
  '....kk......kkkkkk..........................',
  '...kqk......................................',
  '..kqk.......................................',
  '..kqk.......................................',
  '..kIIIIIk...................................',
  '..kIwwwwIk..................................',
  '..kIwttwIk..................................',
  '..kIwwwwIk..................................',
  '..kIIyyIIk..................................',
  '...kkkkkk...................................',
];
// SCATTERED SPIDER 56x28 — colossal spider wearing a call-center headset,
// eight gleaming eyes, web strung from telephone handsets.
const SCATTEREDSPIDER = [
  '....k........kk............kk........k.................',
  '.....k......kqqk..........kqqk......k..................',
  '......k....kqqqqk........kqqqqk....k...................',
  '.......k..kqqqqqqk......kqqqqqqk..k....................',
  '........kkqqqqqqqqkkkkkkqqqqqqqqkk.....................',
  '.......kqqqqqkkkkkkkkkkkkkkqqqqqqk.....................',
  '......kqqqkkmmmmmmmmmmmmmmkkqqqqqk.....................',
  '.....kqqqkmmkqqqqqqqqqqqqkmmkqqqqqk....................',
  '....kqqqqkmkqrrkqqqqqkrrqkqmkqqqqqk....................',
  '....kqqqqkkkqrkkqqqqqkkrqkqkkqqqqqk....................',
  '...kqqqqqqqkqqqqkrrkqqqqqqqkqqqqqqk....................',
  '...kqqqqqqqkqrrkqrkkqkrrqqqkqqqqqqk....................',
  '...kqqqqqqqkqrkkqqqqqkkrqqqkqqqqqqk....................',
  '....kqqqqqqkqqqqkkkkqqqqqqkqqqqqqk.....................',
  '....kqqqqqqkkwwwwwwwwkkqqqkqqqqqk......................',
  '.....kqqqqqkwkkwwwwkkwkqqkqqqqqk.......................',
  '......kqqqqkwwwwwwwwwwkqqqqqqqk........................',
  '.......kkqqqkkkkkkkkkkqqqqqkk..........................',
  '.....kkk.kkqqqqqqqqqqqqkkk.kkk.........................',
  '....kmcmk..kkkkkkkkkkkk...kmcmk........................',
  '...kmccmk................kmccmk........................',
  '...kmkkmk................kmkkmk........................',
  '...km..mk................km..mk........................',
  '...kkkkkk................kkkkkk........................',
];
// THE STUFFER 50x30 — a colossus mortared out of password bricks. Masked
// strings glow in its masonry; stolen keys leak from the cracks; two
// furnace-yellow eyes burn in a vaulted skull.
const STUFFER = [
  '..............kkkkkkkkkkkkkk......................',
  '............kkmccccccccccmkk......................',
  '...........kmccckkkkkkcccccmk.....................',
  '...........kmckeeeeeeeekccmk......................',
  '...........kmkeeyykkeyykekmk......................',
  '...........kmkeeyykkeyykekmk......................',
  '...........kmckeeeeeeeekccmk......................',
  '...........kmcckekekekekccmk......................',
  '......kkkkkkkmmccccccccmmkkkkkkkk.................',
  '....kkmccccmkkmmmmmmmmmmkkmccccmkk................',
  '...kmcwwwwcmkmccckkkkcccmkmcwwwwcmk...............',
  '...kmckkkkcmkmcwwwwwwwwcmkmckkkkcmk....y..........',
  '..kmccccccccmkmckkkkkkcmkmccccccccmk..ky..........',
  '..kmckwwwwkcmkmcwwwwwwcmkmckwwwwkcmk.kyk..........',
  '..kmccccccccmkmckkkkkkcmkmccccccccmk..ky..........',
  '..kmmkkkkkmmkkmccccccccmkkmmkkkkkmmk...y..........',
  '..kmcwwwwcmk.kmmkRRkkmmmk.kmcwwwwcmk..............',
  '..kmckkkkcmk.kmcckRkkccmk.kmckkkkcmk..............',
  '..kmccccccmk.kmcwwwwwwcmk.kmccccccmk..............',
  '..kkmmmmmmkk.kmckkkkkkcmk.kkmmmmmmkk..............',
  '...kmcccccmk.kmccccccccmk.kmcccccmk...............',
  '...kmcwwwcmk.kmmkkkkkkmmk.kmcwwwcmk...............',
  '...kmckkkcmkkkmccccccccmkkkmckkkcmk...............',
  '...kmcccccmkkmcckwwwwkccmkkmcccccmk...............',
  '...kkkkkkkkkkmcccccccccccmkkkkkkkkk...............',
  '............kmmkkkkkkkkmmk........................',
  '..........kkmccccmkkmccccmkk......................',
  '..........kmcccccmkkmcccccmk......................',
  '..........kkkkkkkkkkkkkkkkkk......................',
];
// K0BOLD 56x28 — the shadow agent: an angular AI dragon laced with
// glowing circuit veins, a grin of terminal-cursor teeth, data wisps.
const KOBOLD = [
  '.....k...........................k.....................',
  '......kk.......................kk......................',
  '.......kqk...................kqk.......................',
  '....kkkqqqkkkkkkkkkkkkkkkkkkqqqkkkk....................',
  '...kqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk....................',
  '..kqqqzzkqqqqqdqqqqqqqdqqqqqkzzqqqqk...................',
  '..kqqqzkkqqqqqqqqqqqqqqqqqqqkkzqqqqk...................',
  '..kqqqqqqqdkkkkkkkkkkkkkkdqqqqqqqqqk...................',
  '...kqqqqqkzzzzzzzzzzzzzzzzzzkqqqqqk....................',
  '...kqqqqkzkzkzkzkzkzkzkzkzkzzkqqqqk....................',
  '....kqqqkzzzzzzzzzzzzzzzzzzzzkqqqk.....................',
  '....kqqqqkkkkkkkkkkkkkkkkkkkkqqqqk.....................',
  '...kqqdqqqqqqqqqqqqqqqqqqqqqqqdqqqk....................',
  '..kqqqqqzqqqzqqqqqzqqqqqzqqqqqqqqqk....................',
  '..kqdqqqzqqqzqqqqqzqqqqqzqqqqqdqqqqk...................',
  '.kqqqqkqzqkqzqqkqqzqkqqqzqkqqqqqqqqk...................',
  '.kqqqk.kqk.kqqk..kqk..kqqk.kqqqqqdqk...................',
  '.kqqk...kzk.kqk...kzk..kqk..kqqqqqqk...................',
  '.kqk.....k...kzk...k....kzk..kdqqqqk...................',
  '.kk...........k..........k....kqqqk....................',
  '..k.z.....................z....kkk.....................',
  '...z.z..................z.z............................',
  '....z....................z.............................',
];

// Glitched mirror-Hiro for the deepfake fights: a corrupted copy with
// hostile red eyes and digital static.
const SHADOW_HIRO = [
  '..d.dq.dd.qd.d..',
  '..dqdqqqqdqd.d..',
  '.dqqqqqqqqqqd...',
  'dqqdqqqqqqdqqd..',
  '.dqddddddddqd...',
  '.dddrddddrddd...',
  '..ddrddddrdd....',
  '..ddddkkdddd....',
  '...dddddddd.....',
  '...dqddddqd.....',
  '...qqqqqqqq.....',
  '..qqVqvqqVqq....',
  '.kqqqqvqqqqqk...',
  '.kqqqqvqqqqqk...',
  '..qqqqqqqqqq....',
  '...qqqqqqqq.....',
  '...qqqqqqqq.....',
  '...qqq..qqq.....',
  '...kkk..kkk.....',
  '..kkk....kkk....',
];

export const ENEMY_ART = {
  phishkoi: polish(compile(PHISHKOI)),
  spearphish: polish(compile(SPEARPHISH)),
  angler: polish(compile(ANGLER)),
  lazarus: polish(compile(LAZARUS)),
  doppel: polish(glitchify(compile(SHADOW_HIRO), 7)),
  vishimp: polish(compile(VISHIMP)),
  pushbomber: polish(compile(PUSHBOMBER)),
  keylogger: polish(compile(KEYLOGGER)),
  tokenthief: polish(compile(TOKENTHIEF)),
  simshift: polish(compile(SIMSHIFT)),
  stufferzombie: polish(compile(STUFFERZOMBIE)),
  rogueagent: polish(compile(ROGUEAGENT)),
  phisherking: polish(compile(PHISHERKING)),
  doppelprime: polish(glitchify(compile(SHADOW_HIRO), 13)),
  scatteredspider: polish(compile(SCATTEREDSPIDER)),
  stuffer: polish(compile(STUFFER, { c: 'm', m: 'M' })), // weathered stone
  kobold: polish(compile(KOBOLD)),
};
