// All character art as ASCII pixel grids, compiled to canvases at module load.
import { compile, mirror, outline } from './palette.js';

// ------------------------------------------------- HIRO 16x20 (action suit)
// Matches the v2 mascot art: big tan quill mane, fierce blue eyes,
// black HYPR tactical suit with teal zip, gloves and boots.
const HIRO_DOWN_A = [
  '..h.hY.hh.Yh.h..',
  '..hYhYYYYhYh.h..',
  '.hYYYYYYYYYYh...',
  'hYYhYYYYYYhYYh..',
  '.hYssssssssYh...',
  '.hssbssssbssh...',
  '..ssbssssbss....',
  '..sssskkssss....',
  '...ssssssss.....',
  '...hYssssYh.....',
  '...jjjjjjjj.....',
  '..jjJjtjjJjj....',
  '.kjjjjtjjjjjk...',
  '.kjjjjtjjjjjk...',
  '..jjjjjjjjjj....',
  '...jjjjjjjj.....',
  '...jjjjjjjj.....',
  '...jjj..jjj.....',
  '...kkk..kkk.....',
  '..kkk....kkk....',
];
const HIRO_DOWN_B = HIRO_DOWN_A.slice(0, 17).concat([
  '..jjj....jjj....',
  '..kkk....kkk....',
  '.kkk......kkk...',
]);
const HIRO_UP_A = [
  '..h.hY.hh.Yh.h..',
  '..hYhYYYYhYh.h..',
  '.hYYYYYYYYYYh...',
  'hYYhYYYYYYhYYh..',
  '.hYYYhYYhYYYh...',
  '.hYYYYYYYYYYh...',
  '.hYhYYYYYYhYh...',
  '..hYYYYYYYYh....',
  '...hYYYYYYh.....',
  '...hhYYYYhh.....',
  '...jjjjjjjj.....',
  '..jjJjjjjJjj....',
  '.kjjjjjjjjjjk...',
  '.kjjjjjjjjjjk...',
  '..jjjjjjjjjj....',
  '...jjjjjjjj.....',
  '...jjjjjjjj.....',
  '...jjj..jjj.....',
  '...kkk..kkk.....',
  '..kkk....kkk....',
];
const HIRO_UP_B = HIRO_UP_A.slice(0, 17).concat([
  '..jjj....jjj....',
  '..kkk....kkk....',
  '.kkk......kkk...',
]);
const HIRO_LEFT_A = [
  '....h.hY.h.h....',
  '...hYhYYYhYh....',
  '...hYYYYYYYYh...',
  '..hYYYYYYYhYYh..',
  '..ssYYYYYYYYh...',
  '.ssbsYYYYYYYh...',
  '.ssssYYhYYYh....',
  'kssssYYYYYYh....',
  '.ssssYYYYYh.....',
  '..sshYYYYh......',
  '...jjjjjjjj.....',
  '..jJjjjjjjj.....',
  '..kjjjjjjjj.....',
  '..kjjjjjjjj.....',
  '...jjjjjjjj.....',
  '...jjjjjjj......',
  '...jjjjjjj......',
  '...jjj.jjj......',
  '...kkk.kkk......',
  '..kkk...kkk.....',
];
const HIRO_LEFT_B = HIRO_LEFT_A.slice(0, 16).concat([
  '...jjjjjjj......',
  '..jjj...jjj.....',
  '..kkk...kkk.....',
  '.kkk.....kk.....',
]);

function frames(a, b, swap) { return [outline(compile(a, swap)), outline(compile(b, swap))]; }

export function makeActor(swap = null) {
  const left = frames(HIRO_LEFT_A, HIRO_LEFT_B, swap);
  return {
    down: frames(HIRO_DOWN_A, HIRO_DOWN_B, swap),
    up: frames(HIRO_UP_A, HIRO_UP_B, swap),
    left,
    right: left.map(mirror),
  };
}

export const HIRO = makeActor();

// Detailed battle back-sprite (26x30, drawn 2x in combat): full quill mane,
// shoulder shading, fists clenched, wide stance.
const BATTLE_HIRO_ART = [
  '.....h..hY..hh..Yh..h.....',
  '....hh.hYYh.YY.hYh.hh.....',
  '...hhYhYYYYhYYhYYYhYYh....',
  '..hYYYYYYYYYYYYYYYYYYh....',
  '.hYYhYYYYYYYYYYYYYYhYYh...',
  '.hYYYYYYYYYYYYYYYYYYYYh...',
  'hYYhYYYYYhYYYYhYYYYYhYYh..',
  'hYYYYYYYYYYYYYYYYYYYYYYh..',
  'hYhYYYYYYYYYYYYYYYYYYhYh..',
  '.hYYYYYYhYYYYYYhYYYYYYh...',
  '.hhYYYYYYYYYYYYYYYYYYhh...',
  '..hhYYYYYYYYYYYYYYYYhh....',
  '...hhYYYYYYYYYYYYYYhh.....',
  '....hhYYYYYYYYYYYYhh......',
  '....jjjjjjjjjjjjjjjj......',
  '...jjJJjjjjjjjjjjJJjj.....',
  '..jjjJjjjjjjjjjjjjJjjj....',
  '.kkjJjjjjjjjjjjjjjJjkk....',
  '.kkjjjjjjjjjjjjjjjjjkk....',
  '..kjjjjjjjjjjjjjjjjjk.....',
  '...jjjjjjjjjjjjjjjj.......',
  '...jjjjjjjjjjjjjjjj.......',
  '...jjjjTjjjjjjTjjjj.......',
  '...jjjjjj....jjjjjj.......',
  '...jjjjjj....jjjjjj.......',
  '...jjjjj......jjjjj.......',
  '...kkkkk......kkkkk.......',
  '..kkkkkk......kkkkkk......',
  '..kkkkk........kkkkk......',
];
export const BATTLE_HIRO = outline(compile(BATTLE_HIRO_ART));
// Shadow clone of Hiro for Doppelganger fights.
export const DOPPEL_HIRO = makeActor({ s: 'd', h: 'q', Y: 'q', b: 'r', t: 'v', j: 'q', J: 'q' });

// ----------------------------------------- NPCS 16x20 (GBA-style humans)
// Shaded shirts (b/B swappable), proper pants and shoes, distinct hairdos.
const VILLAGER_M = [
  '....hhhhhh......',
  '...hhhhhhhh.....',
  '..hhhhhhhhhh....',
  '..hhsssssshh....',
  '..hskssssksh....',
  '...ssssssss.....',
  '...sSssssSs.....',
  '....ssssss......',
  '...bbbbbbbb.....',
  '..bbbbbbbbbb....',
  '.sbbbbbbbbbbs...',
  '.sbBbbbbbbBbs...',
  '..bBbbbbbbBb....',
  '...BBBBBBBB.....',
  '...NNNNNNNN.....',
  '...NNN..NNN.....',
  '...NNN..NNN.....',
  '...kkk..kkk.....',
  '..kkkk..kkkk....',
  '................',
];
const VILLAGER_F = [
  '....hhhhhh......',
  '...hhhhhhhh.....',
  '..hhhhhhhhhh....',
  '..hhsssssshh....',
  '.hhsksssskshh...',
  '.hhssssssssshh..',
  '.hhsSssssSsshh..',
  '..hhsssssshh....',
  '...bbbbbbbb.....',
  '..bbbbbbbbbb....',
  '.sbbbbbbbbbbs...',
  '.sbBbbbbbbBbs...',
  '..bbbbbbbbbb....',
  '..bBbbbbbbBb....',
  '..bbbbbbbbbbb...',
  '..BBBBBBBBBBB...',
  '....ss....ss....',
  '....ss....ss....',
  '...kkk...kkk....',
  '................',
];
const KID = [
  '................',
  '................',
  '................',
  '....hhhhhh......',
  '...hhhhhhhh.....',
  '...hhssssshh....',
  '...hsksskssh....',
  '....ssssss......',
  '....bbbbbb......',
  '...sbbbbbbs.....',
  '...sbBbbBbs.....',
  '....bbbbbb......',
  '....NN..NN......',
  '...kkk..kkk.....',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
];
const ELDER = [
  '................',
  '................',
  '....cccccc......',
  '...cccccccc.....',
  '...ccssssscc....',
  '...cskssskc.N...',
  '....ssssssc.N...',
  '....sSssSs..N...',
  '...ddddddd..N...',
  '..ddddddddd.N...',
  '..ddddddddssN...',
  '.sdddddddd..N...',
  '.sddddddddd.N...',
  '..ddddddddd.....',
  '..ddPdddPdd.....',
  '..ddddddddd.....',
  '..PPPPPPPPP.....',
  '...kkk.kkk......',
  '................',
  '................',
];
const CLERK = [
  '...HHHHHHHH.....',
  '..HHHHHHHHHH....',
  '..HHHHHHHHHHH...',
  '..hhsssssshh....',
  '..kskssssksk....',
  '...sssssssskk...',
  '...sSssssSs.k...',
  '....ssssss..k...',
  '...tttttttt.....',
  '..ttcttttctt....',
  '.stTttttttTts...',
  '.stTttttttTts...',
  '..tTttttttTt....',
  '...TTTTTTTT.....',
  '...NNNNNNNN.....',
  '...NNN..NNN.....',
  '...NNN..NNN.....',
  '...kkk..kkk.....',
  '..kkkk..kkkk....',
  '................',
];
const SHOPKEEP = [
  '....hhhhhh......',
  '...hhhhhhhh.....',
  '..hhhhhhhhhh....',
  '..hhsssssshh....',
  '..hskssssksh....',
  '...ssssssss.....',
  '...sSssssSs.....',
  '....ssssss......',
  '...oooooooo.....',
  '..ooccccccoo....',
  '.sooccccccoos...',
  '.sOoccccccoOs...',
  '..Ooccccccoo....',
  '...occcccco.....',
  '...NccccccN.....',
  '...NNN..NNN.....',
  '...NNN..NNN.....',
  '...kkk..kkk.....',
  '..kkkk..kkkk....',
  '................',
];
const SAGE = [
  '....hhhhhh....z.',
  '...hhhhhhhh...n.',
  '..hhssssssh...n.',
  '..kkssssskk...n.',
  '...ssssssss...n.',
  '...sSssssSs...n.',
  '...pppppppp...n.',
  '..pPpppppppP..n.',
  '.sppppppppppsnn.',
  '.spPppppppPps.n.',
  '..pppppppppp..n.',
  '..pPppppppPp..n.',
  '..pppppppppp..n.',
  '..pvpvpvpvpv..n.',
  '..pPppppppPp....',
  '..pppppppppp....',
  '..pPppppppPp....',
  '..PPPPPPPPPP....',
  '...kk....kk.....',
  '................',
];
const GUARD = [
  '......rr........',
  '....mmmmmm...N..',
  '...mmmmmmmm..N..',
  '...mMssssMm..m..',
  '...mskssksm..N..',
  '....ssssss...N..',
  '...MMMMMMMM..N..',
  '..MMmmmmmmMM.N..',
  '..MmmmmmmmmMsN..',
  '.sMmmmpmmmmM.N..',
  '.sMmmmpmmmmM.N..',
  '..MmmmmmmmmM.N..',
  '...MMMMMMMM..N..',
  '...MMMMMMMM.....',
  '...MMM..MMM.....',
  '...MMM..MMM.....',
  '...kkk..kkk.....',
  '..kkkk..kkkk....',
  '................',
  '................',
];
export const NPCS = {
  villager: outline(compile(VILLAGER_M)),
  villagerRed: outline(compile(VILLAGER_M, { b: 'r', B: 'R', h: 'H' })),
  villagerGreen: outline(compile(VILLAGER_M, { b: 'g', B: 'G', h: 'D' })),
  villagerOrange: outline(compile(SHOPKEEP)),
  villagerTeal: outline(compile(VILLAGER_F, { b: 't', B: 'T', h: 'D' })),
  villagerPink: outline(compile(VILLAGER_F, { b: 'f', B: 'R', h: 'y' })),
  elder: outline(compile(ELDER)),
  kid: outline(compile(KID, { h: 'y', b: 'z', B: 'b' })),
  clerk: outline(compile(CLERK)),
  sage: outline(compile(SAGE)),
  guard: outline(compile(GUARD)),
};

// Detailed battle sprites live in enemies.js
export { ENEMY_ART } from './enemies.js';


// --------------------------------------------------- AMBIENT CRITTERS
export const CRITTERS = {
  bunny: compile([
    '.k..k.....',
    'knkknk....',
    'knnnnk....',
    'knknknk...',
    '.knnnnnkk.',
    '.knnnnnnwk',
    '..knn.nnk.',
    '...k...k..',
  ]),
  bird: compile([
    '..kk....',
    '.kttbk..',
    'kytkttk.',
    '.kttttbk',
    '..kbttk.',
    '...ktk..',
    '...k.k..',
  ]),
  crab: compile([
    'k.k....k.k',
    '.kk.kk.kk.',
    '.koooooik.',
    'kowoooowok',
    '.koooooik.',
    '.k.k..k.k.',
  ]),
};

